### ISSUE TITLE
Heads up, https://www.buymeacoffee.com/zhymabekroman is broken

### ISSUE THREAD

**Issue by dragosMC91** [Freedium-cfd/web#21]

**Comment by ZhymabekRoman** [comment]
We regret to inform you that our account on BuyMeACoffee has been suspended due to a violation of their terms of service. This was an unexpected development, and we are currently addressing the matter with utmost priority.

However, our mission at Freedium remains unchanged, and your support is more crucial than ever. We are transitioning to Patreon, a platform that aligns with our values and offers us the freedom to share our work with you.

Please join us on Patreon and continue to support our endeavors. Your contributions are invaluable to us, and we are committed to delivering the quality content you’ve come to expect from Freedium.

Thank you for your understanding and unwavering support.

Support Us on Patreon

Warm regards, The Freedium Team
